### ISSUE TITLE
大佬，出个 spi 接口使用的教程呗！

### ISSUE THREAD

**Issue by xiaoge-404** [3026187875/ROCK_5b#1]
大佬，出个 spi 接口使用的教程呗！
大佬，出个 spi 接口使用的教程呗！
大佬，出个 spi 接口使用的教程呗！

**Comment by leioukupo** [comment]
行，正好我也有一块spi的oled屏幕

**Comment by leioukupo** [comment]
> 大佬，出个 spi 接口使用的教程呗！ 大佬，出个 spi 接口使用的教程呗！ 大佬，出个 spi 接口使用的教程呗！

spi要下个月了，我的板子的spi0是坏的，先寄售后检测下

**Comment by xiaoge-404** [comment]
我闲鱼收的二手，也不知道spi好坏。

**Comment by leioukupo** [comment]
> 我闲鱼收的二手，也不知道spi好坏。

已发spi使用，另外板子spi0没有坏，是抗干扰能力不行，使用跳帽链接自收发正常了

**Comment by xiaoge-404** [comment]
牛逼大佬，研究研究。
